# Generated by Django 5.2.6 on 2025-09-15 16:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aoi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatelliteImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scene_id", models.CharField(max_length=255, unique=True)),
                ("satellite", models.CharField(max_length=50)),
                ("acquisition_date", models.DateTimeField()),
                ("cloud_coverage", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("image_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "satellite_image",
                "ordering": ["-acquisition_date"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("images_processed", models.IntegerField(default=0)),
                ("encroachments_detected", models.IntegerField(default=0)),
                (
                    "aoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_jobs",
                        to="aoi.aoi",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_job",
                "ordering": ["-started_at"],
            },
        ),
    ]
